[package]
edition = "2021"
build = "src/build.rs"
name = "cicada"
version = "0.9.35"
authors = ["Hugo Wang <w@mitnk.com>"]

description = "A simple Bash-like Unix shell."
repository = "https://github.com/mitnk/cicada"
keywords = ["shell", "unix"]
categories = ["command-line-utilities", "command-line-interface", "development-tools"]
license = "MIT"

[profile.release]
strip = true

[lib]
name = "cicada"
path = "src/lib.rs"

[[bin]]
name = "cicada"
doc = false

[dependencies]
errno = "0.2.0"
exec = "0.3.0"
glob = "0.3.0"
lazy_static = "1.3.0"
libc = "0.2.0"
linefeed = "0.6.0"
nix = "0.24.0"
# todo: upgrade pest to 2.4
pest = "=2.3.1"
pest_derive = "2.0"
regex = "1"
yaml-rust = "0.4.0"
uuid = { version = "1.1.2", features = ["serde", "v4"] }
structopt = { version = "0.3", default-features = false }

[dependencies.clap]
version = "3.0.0"
default-features = false
features = ["std"]

[dependencies.rusqlite]
version = "0.27.0"
features = ["bundled"]

[dependencies.time]
version = "0.3"
features = ["local-offset"]

[build-dependencies.time]
version = "0.3"
features = ["local-offset"]
